name: Latest blog post workflow
on:
  schedule:
    - cron: '0 0 * * 0' # Runs every weekly on Sunday.
  workflow_dispatch:
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "20"
          feed_list: "https://medium.com/feed/@madhankumaravelu93, https://medium.com/feed/@madhank_1182"
